/*
 Copyright (c) 2013, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @link      http://buildwithcraft.com
*/
(function(b){var f=Garnish.Base.extend({$alerts:null,$header:null,$nav:null,$overflowNavMenuItem:null,$overflowNavMenuBtn:null,$overflowNavMenu:null,$overflowNavMenuList:null,$notificationWrapper:null,$notificationContainer:null,$contentTabsContainer:null,$main:null,$sidebar:null,$altSidebar:null,$altSidebarNavBtn:null,$altSidebarNavMenu:null,$content:null,$collapsibleTables:null,waitingOnAjax:!1,ajaxQueue:null,navItems:null,totalNavItems:null,visibleNavItems:null,totalNavWidth:null,showingOverflowNavMenu:!1,
showingSidebar:!0,fixedNotifications:!1,fixedSidebar:!1,tabs:null,selectedTab:null,init:function(){this.$alerts=b("#alerts");this.$header=b("#header");this.$nav=b("#nav");this.$notificationWrapper=b("#notifications-wrapper");this.$notificationContainer=b("#notifications");this.$main=b("#main");this.$sidebar=b("#sidebar");this.$content=b("#content");this.$collapsibleTables=this.$content.find("table.collapsible");this.ajaxQueue=[];this.setMaxSidebarHeight();this.navItems=[];this.totalNavWidth=f.baseNavWidth;
var a=this.$nav.children();this.visibleNavItems=this.totalNavItems=a.length;for(var c=0;c<this.totalNavItems;c++){var d=b(a[c]),e=d.width();this.navItems.push(d);this.totalNavWidth+=e}this.addListener(Garnish.$win,"resize","onWindowResize");this.onWindowResize();this.addListener(Garnish.$win,"scroll","onWindowScroll");this.onWindowScroll();a=this.$notificationContainer.children(".error");c=this.$notificationContainer.children(":not(.error)");a.delay(2*f.notificationDuration).fadeOut();c.delay(f.notificationDuration).fadeOut();
this.initContentTabs();document.location.hash&&"undefined"!=typeof this.tabs[document.location.hash]&&this.tabs[document.location.hash].$tab.trigger("click");this.addListener(b(".formsubmit"),"activate",function(a){a=b(a.currentTarget);if(!a.attr("data-confirm")||confirm(a.attr("data-confirm"))){var c=a.data("menu")?a.data("menu").$trigger.closest("form"):a.closest("form");a.attr("data-action")&&b('<input type="hidden" name="action" value="'+a.attr("data-action")+'"/>').appendTo(c);a.attr("data-redirect")&&
b('<input type="hidden" name="redirect" value="'+a.attr("data-redirect")+'"/>').appendTo(c);c.submit()}});this.$alerts.length&&this.initAlerts();b("input[type!=password], textarea").placeholder();var g=b('form[data-saveshortcut="1"]:first');1==g.length&&this.addListener(Garnish.$doc,"keydown",function(a){(a.metaKey||a.ctrlKey)&&a.keyCode==Garnish.S_KEY&&(a.preventDefault(),g.data("saveshortcut-redirect")&&b('<input type="hidden" name="redirect" value="'+g.data("saveshortcut-redirect")+'"/>').appendTo(g),
g.submit());return!0})},initContentTabs:function(){this.$contentTabsContainer=b("#tabs");this.tabs={};this.selectedTab=null;var a=this.$contentTabsContainer.find("a");if(a.length){for(var c=0;c<a.length;c++){var d=b(a[c]),e=d.attr("href");e&&"#"==e.charAt(0)&&(this.tabs[e]={$tab:d,$target:b(e)},this.addListener(d,"activate","selectContentTab"));!this.selectedTab&&d.hasClass("sel")&&(this.selectedTab=e)}this.selectedTab||b(a[0]).trigger("activate")}},setMaxSidebarHeight:function(){this.setMaxSidebarHeight._maxHeight=
this.fixedSidebar?this.$main.offset().top+this.$main.height()-Garnish.$win.scrollTop():this.$main.height();this.$sidebar.css("max-height",this.setMaxSidebarHeight._maxHeight)},onWindowResize:function(){this.onWindowResize._cpWidth=Math.min(Garnish.$win.width(),f.maxWidth);this.updateResponsiveNav();this.updateResponsiveSidebar();this.updateResponsiveTables();this.setMaxSidebarHeight()},updateResponsiveNav:function(){if(this.onWindowResize._cpWidth<this.totalNavWidth)if(this.showingOverflowNavMenu||
(this.$overflowNavMenuBtn?this.$overflowNavMenuItem.show():(this.$overflowNavMenuItem=b("<li/>").appendTo(this.$nav),this.$overflowNavMenuBtn=b('<a class="menubtn" title="'+Craft.t("More")+'">\u2026</a>').appendTo(this.$overflowNavMenuItem),this.$overflowNavMenu=b('<div id="overflow-nav" class="menu" data-align="right"/>').appendTo(this.$overflowNavMenuItem),this.$overflowNavMenuList=b("<ul/>").appendTo(this.$overflowNavMenu),new Garnish.MenuBtn(this.$overflowNavMenuBtn)),this.showingOverflowNavMenu=
!0),this.$nav.height()>f.navHeight){do this.addLastVisibleNavItemToOverflowMenu();while(this.$nav.height()>f.navHeight&&0<this.visibleNavItems)}else{do this.addFirstOverflowNavItemToMainMenu();while(this.$nav.height()==f.navHeight&&this.visibleNavItems<this.totalNavItems);this.addLastVisibleNavItemToOverflowMenu()}else if(this.showingOverflowNavMenu){for(this.$overflowNavMenuItem.hide();this.visibleNavItems<this.totalNavItems;)this.addFirstOverflowNavItemToMainMenu();this.showingOverflowNavMenu=!1}},
updateResponsiveSidebar:function(){if(this.$sidebar.length)if(this.onWindowResize._cpWidth<f.minSidebarWidth){if(this.showingSidebar){this.makeSidebarUnfixed();this.$main.removeClass(f.hasSidebarClass);if(this.$altSidebar)this.$altSidebar.show();else{this.$altSidebar=b('<div id="sidebar-alt"/>').insertAfter(this.$sidebar);for(var a=this.$sidebar.children(),c=0;c<a.length;c++){var d=b(a[c]).clone(!0);if("NAV"==d.prop("nodeName")){var e=d.find(".sel:first").text(),g=d.children();this.$altSidebarNavBtn=
b('<div class="btn menubtn">'+e+"</div>").appendTo(this.$altSidebar);this.$altSidebarNavMenu=b('<div class="menu menulist"/>').appendTo(this.$altSidebar);g.appendTo(this.$altSidebarNavMenu);new Garnish.MenuBtn(this.$altSidebarNavBtn);d.detach()}else d.appendTo(this.$altSidebar)}}this.$sidebar.hide();this.showingSidebar=!1}}else this.showingSidebar||(this.$main.addClass(f.hasSidebarClass),this.$altSidebar.hide(),this.$sidebar.show(),this.showingSidebar=!0,this.updateFixedSidebar())},updateResponsiveTables:function(){this.updateResponsiveTables._contentWidth=
this.$content.width();for(this.updateResponsiveTables._i=0;this.updateResponsiveTables._i<this.$collapsibleTables.length;this.updateResponsiveTables._i++)this.updateResponsiveTables._$table=b(this.$collapsibleTables[this.updateResponsiveTables._i]),this.updateResponsiveTables._check=!1,"undefined"!=typeof this.updateResponsiveTables._lastContentWidth?(this.updateResponsiveTables._isLinear=this.updateResponsiveTables._$table.hasClass("collapsed"),this.updateResponsiveTables._contentWidth>this.updateResponsiveTables._lastContentWidth?
this.updateResponsiveTables._isLinear&&(this.updateResponsiveTables._$table.removeClass("collapsed"),this.updateResponsiveTables._check=!0):this.updateResponsiveTables._isLinear||(this.updateResponsiveTables._check=!0)):this.updateResponsiveTables._check=!0,this.updateResponsiveTables._check&&this.updateResponsiveTables._$table.width()>this.updateResponsiveTables._contentWidth&&this.updateResponsiveTables._$table.addClass("collapsed");this.updateResponsiveTables._lastContentWidth=this.updateResponsiveTables._contentWidth},
addLastVisibleNavItemToOverflowMenu:function(){this.navItems[this.visibleNavItems-1].prependTo(this.$overflowNavMenuList);this.visibleNavItems--},addFirstOverflowNavItemToMainMenu:function(){this.navItems[this.visibleNavItems].insertBefore(this.$overflowNavMenuItem);this.visibleNavItems++},onWindowScroll:function(){this.onWindowScroll._scrollTop=Garnish.$win.scrollTop();this.updateFixedNotifications();this.updateFixedSidebar()},updateFixedNotifications:function(){this.onWindowScroll._headerHeight=
this.$header.height();this.onWindowScroll._scrollTop>this.onWindowScroll._headerHeight?this.fixedNotifications||(this.$notificationWrapper.addClass("fixed"),this.fixedNotifications=!0):this.fixedNotifications&&(this.$notificationWrapper.removeClass("fixed"),this.fixedNotifications=!1)},updateFixedSidebar:function(){this.showingSidebar&&this.$sidebar.length&&(this.onWindowScroll._scrollTop>this.$main.offset().top?(this.makeSidebarFixed(),this.setMaxSidebarHeight()):this.makeSidebarUnfixed())},makeSidebarFixed:function(){this.fixedSidebar||
(this.$sidebar.addClass("fixed"),this.fixedSidebar=!0)},makeSidebarUnfixed:function(){this.fixedSidebar&&(this.$sidebar.removeClass("fixed"),this.fixedSidebar=!1,this.setMaxSidebarHeight())},displayNotification:function(a,c){var d=f.notificationDuration;"error"==a&&(d*=2);b('<div class="notification '+a+'">'+c+"</div>").appendTo(this.$notificationContainer).fadeIn("fast").delay(d).fadeOut()},displayNotice:function(a){this.displayNotification("notice",a)},displayError:function(a){a||(a=Craft.t("An unknown error occurred."));
this.displayNotification("error",a)},deselectContentTab:function(){this.selectedTab&&(this.tabs[this.selectedTab].$tab.removeClass("sel"),this.tabs[this.selectedTab].$target.addClass("hidden"))},selectContentTab:function(a){this.selectedTab&&a.currentTarget==this.tabs[this.selectedTab].$tab[0]||(this.deselectContentTab(),this.selectedTab=b(a.currentTarget).addClass("sel").attr("href"),this.tabs[this.selectedTab].$target.removeClass("hidden"),this.setMaxSidebarHeight())},postActionRequest:function(a,
b,d,e){this.ajaxQueue.push({action:a,data:b,callback:d,options:e});this.waitingOnAjax||this.postNextActionRequest()},postNextActionRequest:function(){this.waitingOnAjax=!0;var a=this.ajaxQueue.shift();Craft.postActionRequest(a.action,a.data,b.proxy(function(b,d,e){a.callback(b,d,e);this.ajaxQueue.length?this.postNextActionRequest():this.waitingOnAjax=!1},this),a.options)},fetchAlerts:function(){this.postActionRequest("app/getCpAlerts",{path:Craft.path},b.proxy(this,"displayAlerts"))},displayAlerts:function(a){if(Garnish.isArray(a)&&
a.length){this.$alerts=b('<ul id="alerts"/>').insertBefore(b("#header"));for(var c=0;c<a.length;c++)b("<li>"+a[c]+"</li>").appendTo(this.$alerts);a=this.$alerts.height();this.$alerts.height(0).animate({height:a},"fast",b.proxy(function(){this.$alerts.height("auto")},this));this.initAlerts()}},initAlerts:function(){var a=this.$alerts.find(".domain-mismatch:first");a.length&&this.addListener(a,"click",b.proxy(function(c){c.preventDefault();confirm(Craft.t("Are you sure you want to transfer your license to this domain?"))&&
Craft.postActionRequest("app/transferLicenseToCurrentDomain",b.proxy(function(b,c){"success"==c&&(b.success?(a.parent().remove(),this.displayNotice(Craft.t("License transferred."))):Craft.cp.displayError(b.error))},this))},this));for(var c=this.$alerts.find('a[class^="shun:"]'),d=0;d<c.length;d++)this.addListener(c[d],"click",b.proxy(function(a){a.preventDefault();var c=b(a.currentTarget);a={message:c.prop("className").substr(5)};Craft.postActionRequest("app/shunCpAlert",a,b.proxy(function(a,b){"success"==
b&&(a.success?c.parent().remove():Craft.cp.displayError(a.error))},this))},this))},checkForUpdates:function(){this.postActionRequest("app/checkForUpdates",{},b.proxy(this,"displayUpdateInfo"))},displayUpdateInfo:function(a){if(a.total){var c=1==a.total?Craft.t("1 update available"):Craft.t("{num} updates available",{num:a.total});b('<li class="updates'+(a.critical?" critical":"")+'"><a data-icon="newstamp" href="'+Craft.getUrl("updates")+'" title="'+c+'"><span>'+a.total+"</span></a></li>").prependTo(b("#header-actions"));
b("#footer-updates").text(c)}this.trigger("checkForUpdates",{updateInfo:a})}},{maxWidth:1051,navHeight:38,baseNavWidth:30,minSidebarWidth:768,hasSidebarClass:"has-sidebar",notificationDuration:2E3});Craft.cp=new f})(jQuery);

//# sourceMappingURL=cp.min.map
