/*
 Copyright (c) 2013, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @link      http://buildwithcraft.com
*/
(function(d){Craft.Dashboard=Garnish.Base.extend({$alerts:null,$container:null,widgets:null,cols:null,colWidth:null,loadingWidget:-1,init:function(){this.$alerts=d("#alerts");this.$container=d("#widgets");this.widgets=[];var a=this.$container.children();this.setCols();for(var b=0;b<a.length;b++){var c=d(a[b]);this.placeWidget(c);this.widgets.push(c)}this.addListener(Garnish.$win,"resize","onWindowResize");"undefined"!=typeof window.getAlerts&&window.getAlerts&&d.getJSON(getAlertsUrl,d.proxy(this,
"displayAlerts"))},onWindowResize:function(){this.setCols()},setCols:function(){var a=Math.floor(this.$container.width()/Craft.Dashboard.minColWidth);0==a&&(a=1);return a!==this.totalCols?(this.totalCols=a,this.refreshCols(),!0):!1},refreshCols:function(){for(var a=0;a<this.widgets.length;a++)this.widgets[a].detach();if(this.cols)for(a=0;a<this.cols.length;a++)this.cols[a].remove();this.cols=[];this.colWidth=Math.floor(1E4/this.totalCols)/100;for(a=0;a<this.totalCols;a++)this.cols[a]=new g(this,a);
for(a=0;a<this.widgets.length;a++)this.placeWidget(this.widgets[a])},placeWidget:function(a){this.getShortestCol().addWidget(a)},getShortestCol:function(){for(var a,b,c=0;c<this.cols.length;c++){var e=this.cols[c],d=this.cols[c].getHeight();if("undefined"==typeof a||d<b)a=e,b=d}return a},getTallestCol:function(){for(var a,b,c=0;c<this.cols.length;c++){var d=this.cols[c],f=this.cols[c].getHeight();if("undefined"==typeof a||f>b)a=d,b=f}return a},onWidgetMove:function(){this.getWidgetHandles();for(var a=
0;a<this.dom.$widgetHandles.length;a++){var b=this.getWidget(a);b&&b.elem.css("zIndex",a+1)}(b=this.getWidget(this.widgetSort.draggeeIndex))&&this.refreshCols(!0)},onWidgetRemove:function(a){var b=d(a.currentTarget).parent();a=b.outerHeight();b.animate({opacity:0,marginBottom:-a},function(){b.remove()});var c=this.getWidgetFromHandle(b);if(c){a=this.$container.offset();var e=c.$elem.offset(),f=c.$elem.width();c.$elem.appendTo(this.$container);c.$elem.css({position:"absolute",display:"block",zIndex:0,
top:e.top-a.top,left:e.left-a.left,width:f});c.$elem.fadeOut(d.proxy(function(){c.$elem.remove()},this))}a=d.inArray(b[0],this.dom.$widgetHandles);this.dom.$widgetHandles.splice(a,1);this.refreshCols(!0)},displayAlerts:function(a,b){if(a&&"success"==b&&a.alerts.length){for(var c=this.$alerts.height(),e=0;e<a.alerts.length;e++){var f=d('<div class="alert"><p>'+a.alerts[e]+"</p></div>");this.$alerts.append(f);f.css({opacity:0});f.delay(100*(e+1)).animate({opacity:1})}e=this.$alerts.height()+20;this.$alerts.height(c);
this.$alerts.animate({height:e},d.proxy(function(){this.$alerts.height("auto")},this))}}},{minColWidth:325});var g=Garnish.Base.extend({dashboard:null,index:null,$outerContainer:null,$innerContainer:null,init:function(a,b){this.dashboard=a;this.index=b;this.$outerContainer=d('<div class="col" style="width: '+this.dashboard.colWidth+'%"/>').appendTo(this.dashboard.$container);this.$innerContainer=d('<div class="col-inner">').appendTo(this.$outerContainer)},getHeight:function(){this.$innerContainer.height("auto");
return this.$outerContainer.height()},setHeight:function(a){this.$innerContainer.height(a)},addWidget:function(a){this.$innerContainer.append(a)},remove:function(){this.$outerContainer.remove()}});Craft.dashboard=new Craft.Dashboard})(jQuery);

//# sourceMappingURL=dashboard.min.map
