/*
 Copyright (c) 2013, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @link      http://buildwithcraft.com
*/
(function(c){Craft.PackageChooser=Garnish.Base.extend({settings:null,$container:null,grid:null,packages:null,clearCcModalTimeout:null,ccModal:null,$ccModalHeader:null,$ccModalSecure:null,$ccModalError:null,$ccModalCancelBtn:null,$ccModalSubmitBtn:null,$ccModalSpinner:null,init:function(b){this.setSettings(b);this.$container=c("#packages");this.grid=new Craft.Grid(this.$container,{minColWidth:175,percentageWidths:!1,fillMode:"grid"});this.packages={};for(b=0;b<this.grid.$items.length;b++){var a=c(this.grid.$items[b]),
d=a.find("h2:first"),e=a.data("package");this.packages[e]={pkg:e,name:d.text(),$container:a,$heading:d,$btnContainer:a.children(".buttons")}}Craft.postActionRequest("app/fetchPackageInfo",c.proxy(this,"initPackages"))},initPackages:function(b,a){for(var d in this.packages)this.packages[d].$btnContainer.html("");if("success"==a)if(b.success)for(d in this.pkgInfo=b.packages,this.packages)"undefined"!=typeof b.packages[d]&&c.extend(this.packages[d],b.packages[d]),this.createButtons(d);else Craft.cp.displayError(b.error)},
createButtons:function(b){var a=this.packages[b];a.$badge&&(a.$badge.remove(),delete a.$badge);a.$btnContainer.html("");if(a.price){if(a.licensed)Craft.hasPackage(b)?a.$badge=c('<div class="badge installed">'+Craft.t("Installed!")+"</div>"):a.$badge=c('<div class="badge uninstalled">'+Craft.t("Uninstalled")+"</div>");else{if(a.trial){var d=Craft.hasPackage(b)?"trial":"uninstalled",e=1==a.daysLeftInTrial?Craft.t("1 day left"):Craft.t("{days} days left",{days:a.daysLeftInTrial});a.$badge=c('<div class="badge '+
d+'">'+e+"</div>")}else Craft.hasPackage(b)&&(a.$badge=c('<div class="badge unlicensed">'+Craft.t("Unlicensed")+"</div>"));d=a.salePrice?'<del class="light">'+this.formatPrice(a.price)+"</del> "+this.formatPrice(a.salePrice):this.formatPrice(a.price);d=c('<div class="btn buy">'+d+"<span>"+Craft.t("Buy")+"</span></div>").appendTo(a.$btnContainer);this.addListener(d,"activate",{pkg:b},"purchasePackage");a.eligibleForTrial&&(d=c('<div class="btn try">'+Craft.t("Try")+"</div>").appendTo(a.$btnContainer),
this.addListener(d,"activate",{pkg:b},"tryPackage"))}a.$badge&&a.$badge.insertBefore(a.$heading);if(a.licensed||a.trial||Craft.hasPackage(b)){d=c('<div class="btn menubtn settings icon"/>').appendTo(a.$btnContainer);a=c('<div class="menu"/>').appendTo(a.$btnContainer);a=c("<ul/>").appendTo(a);a=c("<li/>").appendTo(a);if(Craft.hasPackage(b))var e=Craft.t("Uninstall"),f="uninstall";else e=Craft.t("Install"),f="install";c("<a>"+e+"</a>").appendTo(a).data("package",b).data("action",f);new Garnish.MenuBtn(d,
{onOptionSelect:c.proxy(this,"onOptionSelect")})}}},purchasePackage:function(b){b=b.data.pkg;if(this.ccModal)this.removeListener(this.ccModal.$container,"submit"),this.cleanupCcModal(),this.ccModal.show();else{var a=c(this.settings.modalHtml).appendTo(document.body);this.ccModal=new Garnish.Modal(a,{onShow:c.proxy(this,"onCcModalShow"),onHide:c.proxy(this,"onCcModalHide")});this.$ccModalHeader=a.find("h1:first");this.$ccModalSecure=a.find(".secure:first");this.$ccModalCancelBtn=a.find(".btn.cancel:first");
this.$ccModalSubmitBtn=a.find(".btn.submit:first");this.$ccModalSpinner=a.find(".spinner:first");this.addListener(this.$ccModalCancelBtn,"activate",function(){this.ccModal.hide()})}a=Craft.t("Purchase {package}",{"package":"<em>"+this.packages[b].name+"</em>"});this.$ccModalHeader.html(a);this.addListener(this.ccModal.$container,"submit",{pkg:b},"submitPackagePurchase");Garnish.isMobileBrowser(!0)||setTimeout(function(){c("#cc-name").focus()},500)},cleanupCcModal:function(){this.ccModal.$container.find(".error").removeClass("error");
this.$ccModalError&&this.$ccModalError.remove()},submitPackagePurchase:function(b){b.preventDefault();this.cleanupCcModal();var a=b.data.pkg;b={name:c("#cc-name").val(),number:c("#cc-num").val(),exp_month:c("#cc-month").val(),exp_year:c("#cc-year").val(),cvc:c("#cc-cvc").val()};var d=!0;b.name||(d=!1,c("#cc-name").addClass("error"));Stripe.validateCardNumber(b.number)||(d=!1,c("#cc-num").addClass("error"));Stripe.validateExpiry(b.exp_month,b.exp_year)||(d=!1,c("#cc-month").addClass("error"),c("#cc-year").addClass("error"));
Stripe.validateCVC(b.cvc)||(d=!1,c("#cc-cvc").addClass("error"));d?(this.$ccModalSubmitBtn.addClass("active"),this.$ccModalSpinner.removeClass("hidden"),Stripe.setPublishableKey(this.settings.stripeApiKey),Stripe.createToken(b,c.proxy(function(b,d){d.error?(this.onPurchaseResponse(),Garnish.shake(this.ccModal.$container)):Craft.postActionRequest("app/purchasePackage",{ccTokenId:d.id,"package":a,expectedPrice:this.packages[a].salePrice?this.packages[a].salePrice:this.packages[a].price},c.proxy(this,
"onPurchasePackage"))},this))):Garnish.shake(this.ccModal.$container)},onPurchaseResponse:function(){this.$ccModalSubmitBtn.removeClass("active");this.$ccModalSpinner.addClass("hidden")},onPurchasePackage:function(b,a){this.onPurchaseResponse();if("success"==a)if(b.success){var d=b["package"];this.packages[d].licensed=!0;Craft.hasPackage(d)||Craft.packages.push(d);this.ccModal.hide();this.createButtons(d);Craft.cp.displayNotice(Craft.t("{package} purchased successfully!",{"package":this.packages[d].name}))}else{if(b.errors){var d=
"",e;for(e in b.errors)for(var f=0;f<b.errors[e].length;f++)d&&(d+="<br>"),d+=b.errors[e][f];this.$ccModalError=c('<p class="error centeralign">'+d+"</p>").insertBefore(this.$ccModalSecure)}Garnish.shake(this.ccModal.$container)}},onCcModalShow:function(){this.clearCcModalTimeout&&clearTimeout(this.clearCcModalTimeout)},onCcModalHide:function(){this.clearCcModalTimeout=setTimeout(c.proxy(function(){c("#cc-name").val("");c("#cc-num").val("");c("#cc-month").val("");c("#cc-year").val("");c("#cc-cvc").val("")},
this),Craft.PackageChooser.clearCcModalTimeoutDuration)},tryPackage:function(b){var a=b.data.pkg;confirm(Craft.t("Start your 14-day {package} trial?",{"package":this.packages[a].name}))&&Craft.postActionRequest("app/beginPackageTrial",{"package":a},c.proxy(function(b,c){"success"==c&&(b.success?(Craft.packages.push(a),this.packages[a].trial=!0,this.packages[a].eligibleForTrial=!1,this.packages[a].daysLeftInTrial=14,this.createButtons(a)):Craft.cp.displayError(b.error))},this))},onOptionSelect:function(b){var a=
c(b);b=a.data("package");a=a.data("action");this.performPackageAction(b,a)},performPackageAction:function(b,a,d){Craft.postActionRequest("app/"+a+"Package",{"package":b},c.proxy(function(e,f){if("success"==f)if(e.success){switch(a){case "install":Craft.packages.push(b);break;case "uninstall":var g=c.inArray(b,Craft.packages);Craft.packages.splice(g,1)}this.createButtons(b);"function"==typeof d&&d()}else Craft.cp.displayError(e.error)},this))},formatPrice:function(b){var a=this.settings.USD+Math.floor(b/
100);if(b%=100){for(b=b.toString();2>b.length;)b+="0";a+="."+b}return a}},{clearCcModalTimeoutDuration:3E4})})(jQuery);

//# sourceMappingURL=packages.min.map
