/*
 Copyright (c) 2013, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @link      http://buildwithcraft.com
*/
(function(a){Craft.postActionRequest("update/getAvailableUpdates",function(b,t){var p=a("#loading");p.fadeOut("fast",function(){p.remove();if("success"==t)if(b.error||b.errors){if(b.errors&&b.errors.length)var g=b.errors[0];else b.error&&(g=b.error);a("<div/>").appendTo(Craft.cp.$content).html(g)}else{g=function(b,e){for(var d=0;d<b.length;d++){a("<hr/>").appendTo(Craft.cp.$content);var c=b[d],f=e+" "+c.version;c.build&&(f+=' <span class="light">'+Craft.t("build {build}",{build:c.build})+"</span>");
c.critical&&(f+=' <span class="critical">'+Craft.t("Critical")+"</span>");a("<h2>"+f+"</h2>").appendTo(Craft.cp.$content);a('<div class="notes"/>').appendTo(Craft.cp.$content).html(c.notes)}};if(b.app&&b.app.releases&&b.app.releases.length){var q=function(){a("<iframe/>",{src:b.app.manualDownloadEndpoint}).appendTo(Garnish.$bod).hide()},r=function(){window.location.href=Craft.getUrl("updates/go/craft")};a('<h2 class="heading">'+Craft.t("You\u2019ve got updates!")+"</h2>").appendTo(Craft.cp.$content);
var d=a('<div class="buttons"/>').appendTo(Craft.cp.$content);a('<div class="clear"/>').appendTo(Craft.cp.$content);if(b.app.manualUpdateRequired)var h=a('<div class="btn submit">'+Craft.t("Download")+"</div>").appendTo(d);else{var e=a('<div class="btngroup"/>').appendTo(d),k=a('<div class="btn submit">'+Craft.t("Update")+"</div>").appendTo(e),d=a('<div class="btn submit menubtn"/>').appendTo(e),e=a('<div class="menu" data-align="right"/>').appendTo(e),e=a("<ul/>").appendTo(e),e=a("<li/>").appendTo(e),
h=a("<a>"+Craft.t("Download")+"</a>").appendTo(e);new Garnish.MenuBtn(d)}if(b.app.licenseUpdated){var c,f,l,s,m,n,d=function(b){b.stopPropagation();c?(c.$trigger=a(b.currentTarget),c.show()):(f=a("<form><p>"+Craft.t('Craft\u2019s <a href="http://buildwithcraft.com/license" target="_blank">Terms and Conditions</a> have changed.')+"</p></form>"),s=a("<label> "+Craft.t("I agree.")+" &nbsp;</label>").appendTo(f),m=a('<input type="checkbox"/>').prependTo(s),l=a('<input class="btn submit" type="submit"/>').appendTo(f),
c=new Garnish.HUD(b.currentTarget,f,{hudClass:"hud",triggerSpacing:20,tipWidth:30}),f.on("submit",function(a){a.preventDefault();m.prop("checked")?(n(),c.hide(),m.prop("checked",!1)):Garnish.shake(c.$hud)}));b.currentTarget==h[0]?(l.attr("value",Craft.t("Seriously, download.")),n=q):(l.attr("value",Craft.t("Seriously, update.")),n=r)};h.on("click",d);if("undefined"!=typeof k)k.on("click",d)}else if(h.on("click",q),"undefined"!=typeof k)k.on("click",r);g(b.app.releases,"Craft")}else a('<p id="no-system-updates">'+
Craft.t("No system updates are available.")+"</p>").appendTo(Craft.cp.$content);a("#updates").fadeIn("fast")}})})})(jQuery);

//# sourceMappingURL=updates.min.map
